### ISSUE TITLE
Feature: Add support for Spotify Web Player

### ISSUE THREAD

**Issue by aadibajpai** [SwagLyrics/SwSpotify#10]
SwSpotify is cross-platform, that means we support Windows, macOS and Linux. However, we haven't been able to support the Web Player yet, and doing so would make us completely unstoppable :)

There is an existing Chrome extension that is supposed to be integrated: https://swaglyrics.dev/SwagLyrics-Chrome-Extension 

However, we haven't been able to completely test it out so some work might be needed on both the extension as well as the library itself.

**Comment by flabbet** [comment]
Working on it

**Comment by flabbet** [comment]
Okay, so I've been testing your changes for a while, but in a state you have on your repos, it dosen't work for me. Did you manage to run it successfully, or on what state you got stuck? What have you tested and what not?

**Comment by musabkilic** [comment]
last_played is supposed to be created at the default temp folder of your operating system. What type of errors do you get on content script and background script?

**Comment by flabbet** [comment]
Okay, on linux, last_played is not creating, but on widnows exists. However, it's empty. There isn't any error. On both systems, Spotify appears to be closed at the moment shows.

**Comment by musabkilic** [comment]
I hope the error on windows is fixed after the changing bridge.bat. I'm going to now test it on linux to see what is wrong

**Comment by flabbet** [comment]
Okay, I managed to made it work. #14 
Some improvements still wouldn't be bad and maybe choosing Flask wasn't the ideal choice, but general structure is working.

**Comment by musabkilic** [comment]
Ok, so just to clarify; I think the example they've given on developer.chrome.com is not working correctly. I couldn't even set up the [example](https://chromium.googlesource.com/chromium/src/+/master/chrome/common/extensions/docs/examples/api/nativeMessaging) and my script to install was built on top of the example. I think the real problem is that the native messaging host can't be installed due the error on the .sh file.

**Comment by musabkilic** [comment]
[This](https://github.com/SwagLyrics/SwagLyrics-Chrome-Extension/pull/1/commits/c989522a5ffbcdf7e21a0b8d060290f838e39a80) should fix the problems on linux.

**Comment by aadibajpai** [comment]
@marioortizmanero do you have any thoughts on the 3 implementations? Especially since you add SwSpotify as a dependency, I was wondering which might be the best user experience wise but perhaps speed as well or if size is a factor

**Comment by musabkilic** [comment]
In my opinion, speed is the most important factor to continue SwagLyrics-SwSpotify's legacy: "Very fast". It is what they are known of. But of course, I'm not the one that is going to decide.

**Comment by aadibajpai** [comment]
> In my opinion, speed is the most important factor to continue SwagLyrics-SwSpotify's legacy: "Very fast". It is what they are known of. But of course, I'm not the one that is going to decide.

Sure, but there is the question of the speed vs UX curve—how much of a speed improvement is worth it given the installation. Rest assured, don't worry about it too much 😄

**Comment by marioortizmanero** [comment]
@aadibajpai

Wow, 3 different implementations! That's great.

My project specifically requires a fast and not too resource heavy solution, because it calls the function every second or so. I think that most projects using this module also need something similar. I like the idea of using a timeout because this means the function isn't blocking (which could leave the GUI unresponsive in my case). 

I haven't been able to test any of them, but here are some thoughts:

* @Flabbet solution looks pretty nice and is quite pythonic, but if it actually takes a second to get the status info, I'm not sure if it's the best option.

* @JamesVStone what's the point of using threading in your implementation? You seem to just spawn a single thread when run() is called. Not sure if I'm missing something. 

* @musabkilik implementation can be a good option if the benchmarks in his PR are real.

I'd do an actual benchmark to compare and decide what the best option is. Also, are these extensions limited to Chrome? Can they be made available for Firefox too?

**Comment by musabkilic** [comment]
I haven't test it yet but I think Firefox should support Chrome extension(a couple of changes might need to be done though). I can't wait for the benchmark tests! :)

**Comment by aadibajpai** [comment]
Great work everyone, now just a new release is needed.

**Comment by aadibajpai** [comment]
Done! The extension is at https://chrome.google.com/webstore/detail/swaglyrics-for-spotify/miopldoofdhmipepmnclnoangcdffmlk and the latest version of SwSpotify (v1.2.0) works with it!

Thanks again everyone and sorry for the delay!
